/**
 * `oap config` subcommands.
 *
 * @license Apache-2.0
 */

import { existsSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import {
  ConfigError,
  defaultConfig,
  loadConfig,
} from "@openagentpay/config";

import { firstPositional, flag, pretty, type CommandContext } from "../io.js";

const DEFAULT_PATH = "openagentpay.yaml";

// ============================================================================
//  oap config validate [PATH]
// ============================================================================

export async function cmdConfigValidate(
  argv: ReadonlyArray<string>,
  ctx: CommandContext
): Promise<number> {
  const path = firstPositional(argv) ?? DEFAULT_PATH;
  const abs = resolve(ctx.cwd, path);
  if (!existsSync(abs)) {
    ctx.err(`✘ config not found: ${abs}`);
    return 3;
  }
  try {
    const cfg = loadConfig(abs);
    ctx.log(`✔ config valid: ${abs}`);
    ctx.log(
      `  wallets=${cfg.wallets.length} protocols=${cfg.protocols.length} policies=${cfg.governance.policies.length} tenants=${cfg.tenants.length}`
    );
    ctx.log(`  routing.strategy=${cfg.routing.strategy}`);
    return 0;
  } catch (err) {
    if (err instanceof ConfigError) {
      ctx.err(`✘ ${err.message}`);
      for (const issue of err.issues ?? []) {
        ctx.err(`  - ${issue.path || "(root)"}: ${issue.message}`);
      }
      return 3;
    }
    throw err;
  }
}

// ============================================================================
//  oap config init [--out PATH] [--force]
// ============================================================================

export async function cmdConfigInit(
  argv: ReadonlyArray<string>,
  ctx: CommandContext
): Promise<number> {
  const out = flag(argv, "--out", "-o") ?? DEFAULT_PATH;
  const force = argv.includes("--force") || argv.includes("-f");
  const abs = resolve(ctx.cwd, out);
  if (existsSync(abs) && !force) {
    ctx.err(`✘ ${abs} already exists. Pass --force to overwrite.`);
    return 2;
  }
  const skeleton = defaultConfig();
  // Stringify as a hand-formatted yaml — keep the loader-emitted version in
  // sync with the human-readable example.yaml shipped alongside.
  const yaml = renderSkeletonYaml(skeleton);
  writeFileSync(abs, yaml, "utf8");
  ctx.log(`✔ wrote skeleton: ${abs}`);
  ctx.log(`  edit it, then run:  oap config validate ${out}`);
  return 0;
}

// ============================================================================
//  oap config show [PATH] [--json]
// ============================================================================

export async function cmdConfigShow(
  argv: ReadonlyArray<string>,
  ctx: CommandContext
): Promise<number> {
  const path = firstPositional(argv, ["--out", "-o"]) ?? DEFAULT_PATH;
  const json = argv.includes("--json");
  const abs = resolve(ctx.cwd, path);
  if (!existsSync(abs)) {
    ctx.err(`✘ config not found: ${abs}`);
    return 3;
  }
  try {
    const cfg = loadConfig(abs);
    if (json) {
      ctx.log(pretty(cfg));
    } else {
      ctx.log(`# Effective configuration (with defaults applied)`);
      ctx.log(pretty(cfg));
    }
    return 0;
  } catch (err) {
    if (err instanceof ConfigError) {
      ctx.err(`✘ ${err.message}`);
      for (const issue of err.issues ?? []) {
        ctx.err(`  - ${issue.path || "(root)"}: ${issue.message}`);
      }
      return 3;
    }
    throw err;
  }
}

// ============================================================================
//  Helpers
// ============================================================================

function renderSkeletonYaml(_cfg: ReturnType<typeof defaultConfig>): string {
  // Deterministic, hand-curated skeleton with placeholders + comments.
  return `# openagentpay.yaml — generated by \`oap config init\`
# Docs: https://github.com/neosun100/openAgentPay/blob/main/packages/config/README.md

version: "1"

deployment:
  env: dev

# ----- WALLETS ---------------------------------------------------------------
# Add one entry per provider you want to enable.
# Each \`module\` is a workspace npm package implementing WalletConnector.
wallets: []
  # - provider: hashkey
  #   module: "@openagentpay/wallet-hashkey"
  #   secrets:
  #     privateKey: "env://HASHKEY_TESTNET_AGENT_PRIVATE_KEY"

# ----- PROTOCOLS -------------------------------------------------------------
protocols: []
  # - id: "x402-v1"
  #   module: "@openagentpay/protocol-x402"

# ----- GOVERNANCE ------------------------------------------------------------
governance:
  policies: []
    # - kind: amountThreshold
    #   maxUsd: 50
    # - kind: velocityLimit
    #   windowSeconds: 60
    #   maxCount: 20
  compliance:
    checkers: []
  audit:
    sinks:
      - kind: console

# ----- ROUTING ---------------------------------------------------------------
routing:
  strategy: priority
  fallback: []

# ----- TENANTS ---------------------------------------------------------------
tenants: []
  # - id: dev-sandbox
  #   apiKey: "env://OAP_KEY_DEV"
  #   dailyBudgetUsd: 10
`;
}
